# Generated by Django 4.2.1 on 2023-05-14 13:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('transmission', models.CharField(choices=[('BLA', 'Black'), ('WHI', 'White'), ('RED', 'Red'), ('BLU', 'Blue'), ('SIL', 'Silver')], max_length=3)),
                ('seats', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('fuel', models.CharField(choices=[('PET', 'Petrol'), ('LPG', 'LPG'), ('ELE', 'Electric')], max_length=3)),
                ('power', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.CreateModel(
            name='CarMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=16)),
                ('models', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cars.cardetail')),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmain')),
            ],
        ),
    ]
