# Generated by Django 4.2.1 on 2023-05-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='transmission',
            field=models.CharField(choices=[('AUT', 'Automatic'), ('MAN', 'Manual')], max_length=3),
        ),
    ]
