# Generated by Django 4.2.1 on 2023-05-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cardetail_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetail',
            name='transmission',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual')], max_length=9),
        ),
    ]
